In [2]:
import numpy as np

### Loops

In [9]:
x=40
y=60
if (x>40):
    print("error")
elif(y>60):
    print("error")
else:
    print("your total score is", x+y)

your total score is 100


In [29]:
x=60
y=40
if(x+y==100):
    if(x>60):
        if(x<=60):
            print("you have a B")
        print("error")
    elif(y>40):
        if(y<=40):
            print("you have a D")
        print("error")
    else:
        print("your total score is",x+y)
else:
    print("error, check on both theory and practical")

your total score is 100


In [3]:
practicals=40
theory=60
x=int(input("practicals"))
y=int(input("theory"))
if(x>40):
    print("error")
elif(y>60):
    print("error")
else:
    print("your total score is",x+y)

practicals39
theory55
your total score is 94


In [4]:
if(x+y)>100:
    if(x<=40):
        print("you have a B")
    elif(y<=60):
        print("you have a D")
    else:
        print("error,check on both theory and practical")
else:
    print("your total score is",x+y)


you total score is 94


### initializing different types of arrays



In [ ]:
#all zeros matrix

In [23]:
import numpy as np

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
p=np.zeros((3,3))
p.ndim
p.shape
p.size

9

In [39]:
p=np.zeros((3,3,3))
p.ndim

3

**all ones matrix**



In [41]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
x=np.ones((2,2,3))
x.ndim
x.shape

(2, 2, 3)

In [43]:
x.dtype

dtype('float64')

**any other number**

In [47]:
np.full((2,2),60)

array([[60, 60],
       [60, 60]])

In [49]:
np.full_like(x,50)

array([[[50., 50., 50.],
        [50., 50., 50.]],

       [[50., 50., 50.],
        [50., 50., 50.]]])

In [55]:
np.full(x.shape,50)

array([[[50, 50, 50],
        [50, 50, 50]],

       [[50, 50, 50],
        [50, 50, 50]]])

**random decimals numbers**

In [56]:
np.random.rand(2,3) #creates a matrix of random numbers between 0 and 1

array([[0.46756878, 0.48914575, 0.51327358],
       [0.17087811, 0.69137203, 0.71382307]])

In [57]:
np.random.random_sample(x.shape)

array([[[0.99614912, 0.24350964, 0.090577  ],
        [0.11978261, 0.85452957, 0.90905141]],

       [[0.75130004, 0.01637231, 0.02489848],
        [0.44550263, 0.27774185, 0.24683221]]])

**random integers values**

In [58]:
np.random.randint(5,size=(2,2))

array([[3, 0],
       [4, 3]])

In [59]:
np.random.randint(1,5,size=(2,2))

array([[3, 2],
       [2, 1]])

**identity matrix/eye**

In [61]:
np.identity(5) #diagonal is 1's

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
a=np.eye(4)
print(a.ravel()) #coverts entire array to a single column

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


**lin space**

In [68]:
#generates an array of evenly spread elemets
b=np.linspace(1,5,10)# generates evenly10 spread elements between 1 & 5
print(b)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [70]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [76]:
min(a)
max(a)
sum(a)
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [77]:
a.sum(axis=0)

6

In [96]:
a=np.ones((2,3))
print(a.sum())#returns sum of all elements and axis=none
print(a)
p=a.sum(axis=0)# returns sums of rows
p=a.sum(axis=1)#returns sums of columns

6.0
[[1. 1. 1.]
 [1. 1. 1.]]


In [92]:
p=a.sum(axis=1)
print(p)

[3. 3.]


In [93]:
p=a.sum(axis=0)
print(p)

[2. 2. 2.]


In [3]:
import numpy as np
a=np.arange(25)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [5]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
#extract matrix with elements 0,5,10,15,20
q=a.reshape(5,5)
print(q)
q[0:5,0]
q[0:,:1]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [129]:
q[0:,1:4:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [143]:
q[1:4:2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [8]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
q[3:5:1,3:5:1]

array([[18, 19],
       [23, 24]])

In [9]:
q[4:,0:5:4]

array([[20, 24]])

In [13]:
q[:5,0:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
q[]